services:
  cep-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cep-api:latest
    container_name: cep-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-11050}:8000"
    environment:
      APP_NAME: ${APP_NAME:-CEP API}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      DEBUG: ${DEBUG:-false}
      DB_HOST: cep-api-postgres
      DB_PORT: "5432"
      DB_DATABASE: ${DB_NAME:-cep-api}
      DB_USERNAME: ${DB_USER:-cep-api}
      DB_PASSWORD: ${DB_PASS:-changeme}
    depends_on:
      - cep-api-postgres
    networks:
      - cep-api-net

  cep-api-postgres:
    image: postgres:16
    container_name: cep-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-cep-api}
      POSTGRES_DB: ${DB_NAME:-cep-api}
      POSTGRES_PASSWORD: ${DB_PASS:-changeme}
      TZ: America/Sao_Paulo
    volumes:
      - cep-api-pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "${DB_PORT:-11055}:5432"
    networks:
      - cep-api-net

volumes:
  cep-api-pgdata:

networks:
  cep-api-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.12.0/28
          gateway: 172.28.12.1
